version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: blog_be
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: 'blog'              # name of database
      MYSQL_ALLOW_EMPTY_PASSWORD: true    # password for root user
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '3308:3306'              # host port 3306 is mapper to docker 
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d